# Generated by Django 4.2.2 on 2023-06-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_is_admin_user_is_admin_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Images/')),
                ('detail', models.CharField(max_length=2000)),
                ('ingredients', models.CharField(max_length=500)),
                ('veg', models.BooleanField(default=True)),
                ('amount', models.BigIntegerField()),
                ('energy', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('protein', models.IntegerField()),
                ('fibre', models.IntegerField()),
                ('fat', models.IntegerField()),
            ],
        ),
    ]
