# Generated by Django 4.2.2 on 2023-06-30 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_menuitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuItems',
            new_name='MenuItem',
        ),
    ]
