# Generated by Django 4.2.2 on 2023-07-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_menuitem_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address1',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='order',
            name='address2',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='post_code',
            field=models.BigIntegerField(null=True),
        ),
    ]
