# Generated by Django 4.2.2 on 2023-07-31 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_address_order_remove_order_address1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address_Order',
        ),
    ]
