# Generated by Django 4.2.2 on 2023-07-04 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_menuitem_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='slug',
        ),
    ]
