# Generated by Django 4.2.2 on 2023-07-10 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_addcartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCartItemModel',
            fields=[
                ('cart_no', models.AutoField(primary_key=True, serialize=False)),
                ('qty', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.menuitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AddCartItem',
        ),
    ]
