# Generated by Django 4.2.2 on 2023-07-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_addcartitemmodel_delete_addcartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addcartitemmodel',
            old_name='item',
            new_name='name',
        ),
    ]
